server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: quora-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/quora
    username: enterprisedb
    password: unibrain

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect